### ISSUE TITLE
[FR] Look into FILAMENT RUNOUT DISTANCE

### ISSUE THREAD

**Issue by TwinkieXLII** [JGMaker3dofficial/artistd#15]
### Description

Where the filament runout sensors are mounted far away from the extruder, it may be beneficial to configure some extra filament to be used when the runout sensors are triggered. 

#### Additional Information

Not sure which version of marlin this was introduced in.   but I do know there may be an LcD configuration item HAS_FILAMENT_RUNOUT_DISTANCE.

**Comment by mikejr83** [comment]
Wouldn't it be awesome if we could say here's the "configured" runout length - the current z height?
