### ISSUE TITLE
[BUG] Running G28 in IDEX Duplication Mode Causes E1 to Do "Bad Stuff"

### ISSUE THREAD

**Issue by mikejr83** [JGMaker3dofficial/artistd#26]
### Bug Description

When the printer is issued a `G28` command when in IDEX Duplication mode the E1 extruder tries to go past its limit.

### My Configurations

Appears to be in stock JGMaker firmware and in my custom firmware from 2.07.2

### Steps to Reproduce

1. In the menu for the printer select Configuration -> IDEX Mode -> Duplication. 
2. Load a print from SD card where the print homes the printer with a G28
3. Cover your ears

**Expected behavior:**

The extruders should home. I'm not quite sure what this should be in duplication or mirror mode. They should definitely know what their endstops are and shouldn't attempt to exceed them.

**Actual behavior:** 

Appears the E1 is trying to move too far to the left.

**Comment by mikejr83** [comment]
Update: This appears to be an issue with ordering in the GCODE start-up for a print. I now believe this isn't a bug with JGMaker's version of the Marlin firmware but an issue with upstream Marlin. It appears that the extruders are not respecting the soft and hard limits of the machine.

**Comment by bodinjm** [comment]
Still doing it on my machine, I look into the GCODE but can't find the root of the problem

**Comment by mikejr83** [comment]
@bodinjm The best I can figure is there is some issue upstream, in Marlin. If you create another printer in your slicing software for duplication mode you can use this start gcode: https://gist.github.com/mikejr83/97b7684d1f507243d08094e4bd718ba2 and will not have the issue.

**Comment by bodinjm** [comment]
OK thanks, I was planing to create a "duplication mode" slicer config with half the plate and your start G-Code, I will tell you then. Thanks for your help and "devotion to the cause" of this printer. We will tame the horse !!
