### ISSUE TITLE
[FR] Don't Move Bed on Nozzle Change.  

### ISSUE THREAD

**Issue by TwinkieXLII** [JGMaker3dofficial/artistd#28]
### Description

I don't think there's a reason to move the bed on a filament change. 

#### Additional Information

This is a configuable feature starting with Marlin 2.0.6

**Comment by TwinkieXLII** [comment]
Is this on the M600 code?

**Comment by GeraldHebinck** [comment]
M600 uses the NOZZLE_PARK_FEATURE

to disable bed movement for M600, enable NOZZLE_PARK_X_ONLY.
That should disable the bed movement.

**Comment by TwinkieXLII** [comment]
I want to double check that this has been fixed?
