### ISSUE TITLE
[BUG] Under Extrusion after flashing?

### ISSUE THREAD

**Issue by inspectionsbybob** [JGMaker3dofficial/artistd#43]
Ok, I am having weird problems...
Looks like under extrusion, way under...

When I measure out 100mm of filament, and tell it to extrude 100mm, I get about 75% of what I am supposed to, NO MATTER WHAT I PUT IN.

200 steps/mm or 400 step/mm I get about 75-80mm.
It is consistent between E1 and E2, and different filaments, with and without the friction of the run-out detector.

Do I need to "save" or go through some specific steps so the new values "take".  I am powering down for a bit (dinner) and then I will try a different routine exiting all the way out between changes.   

For Generic PLA, what should I expect as a value for Steps/mm for 1.75mm filament?  I was happy at around 100 and then I flashed and I can get my flow up...

**Comment by inspectionsbybob** [comment]
Ok, quick update.
NONE of my edits were taking.  I powered down, had a (non-alcoholic) drink and powered up.  The E-Step values were back to where I began.  So when you change the E-Step you need to do something to "update" the values.  Not sure what step is yet... but I have a bit more time tonight.

**Comment by nmavor** [comment]
did you save? using M500?

**Comment by inspectionsbybob** [comment]
No, I am using the menu...
Had to Exit (go up)  2 config menus and then "SAVE" and that gave me a "Configuration saved" on the main menu.  SEEMS to be happier.  Trying a test print to see if that fixes my under extrusion....

**Comment by inspectionsbybob** [comment]
Ok, most of my problems SEEM to be under extrusion.  Flashing lost some E-step values, and then I am unfamiliar with -THIS- software, so my edits didn't take, -MY- issue, or documentation.

Under extrusion exuberates any bed unlevel issues...  No that I am at least close to extruding what I should be, the bed is behaving "Better".  I made a TEST GRID of 2mm bars in a checkerboard pattern.  It is a torture test for bed adhesion...  I need some sleep and then I will re-load some good filament and try to level the bed tomorrow, but now that values are "sticking" I am getting closer and closer.

DOCUMENTATION.  It was not clear that you need to go UP TWO LEVELS and SAVE !

Go ahead and CLOSE this one!

**Comment by mikejr83** [comment]
Glad you figured it out!

As an FYI, the version of the firmware that came on my machine, and I think many of the first 200, did not support saving to EEPROM. It saved to the SD card. You could get interesting results similar to what you describe. Once you're comfortable with your machine, I highly recommend moving to one of the beta releases. I have a feeling that many of the issues that people are reporting are due to the age of the underlying Marlin version that shipped with these printer.
